# Generated by Django 3.2 on 2023-06-14 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modules.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cellphone', models.CharField(max_length=100, verbose_name='Celular')),
                ('document_number', models.CharField(max_length=100, verbose_name='Documento')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('ruc', models.CharField(max_length=100, verbose_name='RUC')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.event')),
            ],
            options={
                'verbose_name': 'Inscripciones',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, default=None, max_length=250, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Apellidos')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 6, 13, 22, 49, 39, 591076), null=True, verbose_name='Última de modificación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', modules.users.models.UserManager()),
            ],
        ),
    ]
