# Generated by Django 3.2 on 2023-06-14 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 23, 7, 50, 954806), null=True, verbose_name='Última de modificación'),
        ),
    ]
