# Generated by Django 3.2 on 2023-06-14 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 23, 36, 50, 575188), null=True, verbose_name='Última de modificación'),
        ),
    ]
