# Generated by Django 3.2 on 2023-06-14 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='ruc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 1, 20, 32, 332761), null=True, verbose_name='Última de modificación'),
        ),
    ]
