# Generated by Django 3.2 on 2023-06-14 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_socialnetwork_icon_hover'),
        ('users', '0014_auto_20230614_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 11, 0, 5, 38332), null=True, verbose_name='Última de modificación'),
        ),
    ]
