# Generated by Django 3.2 on 2023-06-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230614_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 9, 34, 29, 106681), null=True, verbose_name='Última de modificación'),
        ),
    ]
