# Generated by Django 3.2 on 2023-06-15 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 17, 57, 56, 510812), null=True, verbose_name='Última de modificación'),
        ),
    ]
