# Generated by Django 3.2 on 2023-08-26 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230616_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 8, 2, 42, 766561), null=True, verbose_name='Última de modificación'),
        ),
    ]
