# Generated by Django 3.2 on 2023-08-26 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='response_infobip',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Respuesta Infobip'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 8, 10, 18, 251334), null=True, verbose_name='Última de modificación'),
        ),
    ]
