# Generated by Django 5.2.3 on 2025-06-12 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230826_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 1, 50, 10, 223936), null=True, verbose_name='Última de modificación'),
        ),
    ]
