# Generated by Django 5.2.3 on 2025-06-18 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 23, 12, 13, 60998), null=True, verbose_name='Última de modificación'),
        ),
    ]
