# Generated by Django 5.2.3 on 2025-06-23 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='publicidad',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Acepto el envío de publicidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 10, 36, 41, 883489), null=True, verbose_name='Última de modificación'),
        ),
    ]
