# Generated by Django 5.2.3 on 2025-08-17 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_inscriptions_publicidad_alter_user_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='flag_endinscriptions',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inscripciones Abiertas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 21, 26, 59, 321504), null=True, verbose_name='Última de modificación'),
        ),
    ]
