# Generated by Django 5.2.3 on 2025-08-17 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_inscriptions_flag_endinscriptions_alter_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 21, 27, 18, 762772), null=True, verbose_name='Última de modificación'),
        ),
    ]
