# Generated by Django 5.2.3 on 2025-08-17 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptions',
            name='flag_endinscriptions',
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 21, 32, 5, 594603), null=True, verbose_name='Última de modificación'),
        ),
    ]
