# Generated by Django 5.2.3 on 2025-08-18 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_inscriptions_flag_endinscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 9, 41, 1, 107614), null=True, verbose_name='Última de modificación'),
        ),
    ]
