# Generated by Django 3.2 on 2023-06-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('background', models.ImageField(upload_to='page')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('_blank', '_blank'), ('self', 'self')], default='self', max_length=30, verbose_name='Destino')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_networks', verbose_name='Icono')),
                ('network', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn')], default='Facebook', max_length=30, verbose_name='Red social')),
                ('url', models.URLField(max_length=140, null=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
    ]
