# Generated by Django 3.2 on 2023-06-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230613_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventteacher',
            name='topic',
        ),
        migrations.AddField(
            model_name='eventteacher',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='eventteacher',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='eventteacher',
            name='topics_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Título topicos'),
        ),
    ]
