# Generated by Django 3.2 on 2023-06-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20230614_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.eventteacher'),
        ),
    ]
