# Generated by Django 3.2 on 2023-06-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_topic_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='teacher',
        ),
        migrations.AddField(
            model_name='eventteacher',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='content.Topic', verbose_name='topicos'),
        ),
    ]
