# Generated by Django 3.2 on 2023-06-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_topic_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='copyrigth',
        ),
    ]
