# Generated by Django 3.2 on 2023-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_home_copyrigth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
    ]
