# Generated by Django 3.2 on 2023-06-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_event_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='background',
            new_name='image',
        ),
    ]
