# Generated by Django 3.2 on 2023-06-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventteacher',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teacher', to='content.event'),
        ),
        migrations.AlterField(
            model_name='eventteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_event', to='content.teacher'),
        ),
    ]
