# Generated by Django 3.2 on 2023-06-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20230614_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='icon_hover',
            field=models.ImageField(blank=True, null=True, upload_to='social_networks', verbose_name='Icono (hover)'),
        ),
    ]
