# Generated by Django 3.2 on 2023-06-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_socialnetwork_icon_hover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Conferencista', 'verbose_name_plural': 'Conferencistas'},
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='eventteacher',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teacher', to='content.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_event', to='content.teacher', verbose_name='Conferencista'),
        ),
    ]
