# Generated by Django 3.2 on 2023-06-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20230615_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['the_order', '-date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
