# Generated by Django 3.2 on 2023-06-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20230615_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['the_order'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
