# Generated by Django 3.2 on 2023-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='infobip_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Código Infobip'),
        ),
    ]
