# Generated by Django 5.2.3 on 2025-06-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_event_infobip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_event',
            field=models.ImageField(null=True, upload_to='logo_event'),
        ),
    ]
