# Generated by Django 5.2.3 on 2025-08-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_temas_alter_event_logo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flag_endinscriptions',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inscripciones Abiertas'),
        ),
    ]
