# Generated by Django 5.2.3 on 2025-08-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_event_flag_endinscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flag_endinscriptions',
            field=models.BooleanField(default=False, verbose_name='Inscripciones Abiertas'),
        ),
    ]
